In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
import datetime
import statistics
import math
import numpy as np

## Aux functions

In [2]:
def clean_dataset(df):
    assert isinstance(df, pd.DataFrame) 
    df.dropna(inplace=True)
    indices_to_keep = ~df.isin([np.nan, np.inf, -np.inf]).any(1)
    return df[indices_to_keep].astype(np.float64)

In [3]:
def cal_nrmse(rmse, y):
    x = max(y)-min(y)
    return (rmse/x)

## Dataset Energy HPC

In [4]:
filename = 'wim_ae_wmvfts_dim_fsets_hpc.csv'
data = pd.read_csv(filename)
data.dropna(inplace=True)
data

,dimensions,fuzzy_sets,window,rmse,nrmse,mape,smape,mae
0,2,10,0,7.012145e-01,9.307333e-02,1.048531e+02,2.519790e+01,5.419348e-01
1,2,10,2276,5.360549e-01,6.888395e-02,7.775062e+01,2.165777e+01,3.988943e-01
2,2,10,4552,4.758449e-01,7.694774e-02,1.189687e+02,2.844557e+01,3.691864e-01
3,2,10,6828,4.913264e-01,8.057173e-02,1.798989e+02,3.797632e+01,4.281838e-01
4,2,10,9104,4.814760e-01,1.039905e-01,1.524895e+02,3.448373e+01,3.787391e-01
...,...,...,...,...,...,...,...,...
595,5,50,56900,2.553217e-16,4.108814e-17,1.236723e-14,6.183616e-15,1.387779e-16
596,5,50,59176,5.603849e-04,7.620138e-05,1.515234e-02,7.606430e-03,1.166419e-02
597,5,50,61452,2.415597e-05,1.308558e-05,4.150291e-04,2.072698e-04,1.012671e-06
598,5,50,63728,2.075698e-16,3.526500e-17,1.072657e-14,5.363283e-15,8.637590e-03
599,5,50,66004,2.178390e-16,2.313498e-17,1.105066e-14,5.525332e-15,1.490604e-02

In [5]:
#data.loc[(data['dimensions'] == 2) & (data['fuzzy_sets'] == 10)]

In [6]:
dimensions = [2,3,4,5]
fuzzy_sets = [10,20,30,40,50]

final_result = {
    "dimensions": [],
    "fuzzy_sets": [],
    "rmse": [],
    "mae": [],
    "mape": [],
    "smape": [],
    "nrmse":[],
    "rmse_std": [],
    "mae_std": [],
    "mape_std": [],
    "smape_std": [],
    "nrmse_std": []
}

for dim in dimensions:
    for fs in fuzzy_sets:
        measures = data.loc[(data['dimensions'] == dim) & (data['fuzzy_sets'] == fs)]
        final_result["dimensions"].append(dim)
        final_result["fuzzy_sets"].append(fs)
        
        rmse = round(statistics.mean(measures['rmse']),3)
        mape = round(statistics.mean(measures['mape']),3)
        smape = round(statistics.mean(measures['smape']),3)
        mae = round(statistics.mean(measures['mae']),3)
        nrmse = round(statistics.mean(measures['nrmse']),3)
        
        rmse_std = round(statistics.stdev(measures['rmse']),3)
        mape_std = round(statistics.stdev(measures['mape']),3)
        smape_std = round(statistics.stdev(measures['smape']),3)
        mae_std = round(statistics.stdev(measures['mae']),3)
        nrmse_std = round(statistics.stdev(measures['nrmse']),3)
        
        final_result["rmse"].append(rmse)
        final_result["mape"].append(mape)
        final_result["smape"].append(smape)
        final_result["mae"].append(mae)
        final_result["nrmse"].append(nrmse)
        
        final_result["rmse_std"].append(rmse_std)
        final_result["mape_std"].append(mape_std)
        final_result["smape_std"].append(smape_std)
        final_result["mae_std"].append(mae_std)
        final_result["nrmse_std"].append(nrmse_std)
        
        print(f'Results: {(dim,fs,rmse,mae,mape,smape,nrmse)}')
        
        
final_measures_ae = pd.DataFrame(final_result) 

print("Statistics AE-WMVFTS (test): ")
final_measures_ae

Results: (2, 10, 0.556, 0.428, 103.394, 27.086, 0.104)
Results: (2, 20, 0.43, 0.307, 70.099, 21.351, 0.08)
Results: (2, 30, 0.396, 0.294, 64.52, 20.421, 0.073)
Results: (2, 40, 0.352, 0.254, 55.072, 17.662, 0.064)
Results: (2, 50, 0.369, 0.272, 63.554, 19.111, 0.07)
Results: (3, 10, 0.528, 0.424, 104.344, 27.232, 0.101)
Results: (3, 20, 0.317, 0.241, 56.548, 17.96, 0.062)
Results: (3, 30, 0.206, 0.136, 29.725, 10.547, 0.044)
Results: (3, 40, 0.149, 0.078, 14.108, 5.666, 0.03)
Results: (3, 50, 0.093, 0.037, 6.444, 2.456, 0.019)
Results: (4, 10, 0.422, 0.346, 84.954, 23.617, 0.083)
Results: (4, 20, 0.133, 0.098, 29.106, 9.673, 0.033)
Results: (4, 30, 0.065, 0.038, 7.425, 3.187, 0.014)
Results: (4, 40, 0.021, 0.011, 2.08, 0.889, 0.005)
Results: (4, 50, 0.019, 0.007, 0.697, 0.321, 0.005)
Results: (5, 10, 0.253, 0.199, 51.635, 16.012, 0.053)
Results: (5, 20, 0.053, 0.038, 13.018, 4.073, 0.017)
Results: (5, 30, 0.013, 0.009, 1.803, 0.75, 0.003)
Results: (5, 40, 0.005, 0.004, 0.291, 0.141, 0.001)
Results: (5, 50, 0.001, 0.003, 0.124, 0.057, 0.0)
Statistics AE-WMVFTS (test):

,dimensions,fuzzy_sets,rmse,mae,mape,smape,nrmse,rmse_std,mae_std,mape_std,smape_std,nrmse_std
0,2,10,0.556,0.428,103.394,27.086,0.104,0.105,0.069,45.556,7.221,0.059
1,2,20,0.430,0.307,70.099,21.351,0.080,0.093,0.060,37.291,7.301,0.045
2,2,30,0.396,0.294,64.520,20.421,0.073,0.113,0.083,31.816,6.807,0.037
3,2,40,0.352,0.254,55.072,17.662,0.064,0.134,0.097,32.071,6.712,0.032
4,2,50,0.369,0.272,63.554,19.111,0.070,0.142,0.110,41.078,7.315,0.045
5,3,10,0.528,0.424,104.344,27.232,0.101,0.099,0.070,47.200,7.314,0.065
6,3,20,0.317,0.241,56.548,17.960,0.062,0.080,0.060,36.074,7.952,0.045
7,3,30,0.206,0.136,29.725,10.547,0.044,0.073,0.064,31.167,7.931,0.050
8,3,40,0.149,0.078,14.108,5.666,0.030,0.068,0.041,10.918,3.718,0.027
9,3,50,0.093,0.037,6.444,2.456,0.019,0.069,0.027,8.483,2.517,0.019
10,4,10,0.422,0.346,84.954,23.617,0.083,0.136,0.108,48.668,8.093,0.069
11,4,20,0.133,0.098,29.106,9.673,0.033,0.077,0.071,37.539,9.694,0.052
12,4,30,0.065,0.038,7.425,3.187,0.014,0.051,0.034,9.543,3.770,0.020
13,4,40,0.021,0.011,2.080,0.889,0.005,0.029,0.017,4.785,1.942,0.011
14,4,50,0.019,0.007,0.697,0.321,0.005,0.029,0.010,1.521,0.672,0.009
15,5,10,0.253,0.199,51.635,16.012,0.053,0.106,0.096,40.525,9.612,0.053
16,5,20,0.053,0.038,13.018,4.073,0.017,0.064,0.052,32.234,8.012,0.049
17,5,30,0.013,0.009,1.803,0.750,0.003,0.025,0.017,5.577,2.201,0.007
18,5,40,0.005,0.004,0.291,0.141,0.001,0.008,0.007,0.837,0.395,0.003
19,5,50,0.001,0.003,0.124,0.057,0.000,0.005,0.006,0.569,0.259,0.001

In [9]:
final_measures_ae

,dimensions,fuzzy_sets,rmse,mae,mape,smape,nrmse,rmse_std,mae_std,mape_std,smape_std,nrmse_std
0,2,10,0.556,0.428,103.394,27.086,0.104,0.105,0.069,45.556,7.221,0.059
1,2,20,0.430,0.307,70.099,21.351,0.080,0.093,0.060,37.291,7.301,0.045
2,2,30,0.396,0.294,64.520,20.421,0.073,0.113,0.083,31.816,6.807,0.037
3,2,40,0.352,0.254,55.072,17.662,0.064,0.134,0.097,32.071,6.712,0.032
4,2,50,0.369,0.272,63.554,19.111,0.070,0.142,0.110,41.078,7.315,0.045
5,3,10,0.528,0.424,104.344,27.232,0.101,0.099,0.070,47.200,7.314,0.065
6,3,20,0.317,0.241,56.548,17.960,0.062,0.080,0.060,36.074,7.952,0.045
7,3,30,0.206,0.136,29.725,10.547,0.044,0.073,0.064,31.167,7.931,0.050
8,3,40,0.149,0.078,14.108,5.666,0.030,0.068,0.041,10.918,3.718,0.027
9,3,50,0.093,0.037,6.444,2.456,0.019,0.069,0.027,8.483,2.517,0.019
10,4,10,0.422,0.346,84.954,23.617,0.083,0.136,0.108,48.668,8.093,0.069
11,4,20,0.133,0.098,29.106,9.673,0.033,0.077,0.071,37.539,9.694,0.052
12,4,30,0.065,0.038,7.425,3.187,0.014,0.051,0.034,9.543,3.770,0.020
13,4,40,0.021,0.011,2.080,0.889,0.005,0.029,0.017,4.785,1.942,0.011
14,4,50,0.019,0.007,0.697,0.321,0.005,0.029,0.010,1.521,0.672,0.009
15,5,10,0.253,0.199,51.635,16.012,0.053,0.106,0.096,40.525,9.612,0.053
16,5,20,0.053,0.038,13.018,4.073,0.017,0.064,0.052,32.234,8.012,0.049
17,5,30,0.013,0.009,1.803,0.750,0.003,0.025,0.017,5.577,2.201,0.007
18,5,40,0.005,0.004,0.291,0.141,0.001,0.008,0.007,0.837,0.395,0.003
19,5,50,0.001,0.003,0.124,0.057,0.000,0.005,0.006,0.569,0.259,0.001

In [10]:
final_measures_ae.to_csv (r'ae_wmvfts_dim_fsets_hpc.csv', index = False, header=True)